Edfj 105 Edfj106 완료
ballet-for-all/ballet_for_all_flutter pull request #25
Opened 2023-08-04 05:12 UTC by dlaehdrlf4

2023-08-05 03:30 UTC, ghrud92 commented
음.. 정말 굉장히 크군요..
shared preferences와 splash는 상태관리 교체와 상관이 없으니 빼주실 수 있을까요?

그리고 지금 제가 pr 받았을 때는 빌드가 일단 안되는데, 혹시 Flutter 버전을 업그레이드 해야하나요?
만약 버전 올려야 한다면 .fvm/fvm_config.json 부분도 수정 부탁드립니다.

머지 컨플릭트도 해결해주세요!

2023-08-05 09:16 UTC, dlaehdrlf4 commented
splash랑 sharedpreferences 제거하였고 플러터 버전도 변경하였습니다.
충돌도 해결하여 올렸습니다.

2023-08-05 10:38 UTC, ghrud92 commented on lib/page/location/pages.dart
> +class LocationPage1 extends GetView<LocationController> {
1 지워주셔도 될 것 같습니다

2023-08-05 10:55 UTC, ghrud92 requested changes
제가 아직 몇 파일 안보기는 했는데, 전체적으로 자동 포멧팅이 안된 것 같네요
lint warning은 잘 뜨시나요?

2023-08-05 10:55 UTC, ghrud92 commented on lib/page/location/pages.dart
> +class LocationPage1 extends GetView<LocationController> {
1 지워주셔도 될 것 같습니다

2023-08-05 10:55 UTC, ghrud92 commented on lib/page/location/pages.dart
> +import '../../routes/app_routes.dart';
안쓰이는 import 지워주세요

2023-08-05 10:55 UTC, ghrud92 commented on lib/page/location/pages.dart
> +import '../sample_page.dart';
여기도요

2023-08-05 10:55 UTC, ghrud92 commented on lib/page/location/pages.dart
> +  Scaffold(
Lint 상으로 Scaffold가 윗 줄 ()=> 옆에 붙어야 할 것 같은데, 이게 혹시 자동으로 포메팅이 안되시나요?

2023-08-05 10:55 UTC, ghrud92 commented on lib/page/location/pages.dart
> +  final _borderSide = const BorderSide(color: Color(0xFFCCCCCC), width: 1);
GetView가 Stateless 위젯인거죠?
그래서 const constructor를 갖는게 맞는 것 같은데, 그래서 여기 warning이 뜨네요.
어차피 const 선언이고, 크게 연산이 필요한 작업은 아니니 build() 안에서 하면 어떨까요?
아니면 get 함수 형태로?

2023-08-05 10:55 UTC, ghrud92 commented on lib/page/location/pages.dart
> +
빈 줄 삭제해주세요

2023-08-05 10:55 UTC, ghrud92 commented on lib/page/location/pages.dart
> +
빈 줄 삭제해주세요

2023-08-05 10:55 UTC, ghrud92 commented on lib/page/location/pages.dart
> +
빈 줄 삭제해주세요

2023-08-05 10:55 UTC, ghrud92 commented on lib/page/location/controller.dart
> +import 'package:flutter_bloc/flutter_bloc.dart';
안쓰이는 import 제거해주세요

2023-08-06 15:20 UTC, dlaehdrlf4 commented
import 및 코드 정렬 하여 다시 merge 진행하였습니다.

2023-08-09 10:06 UTC, ghrud92 requested changes
코맨트 남긴 것 중 해결된 것들은 resolve 부탁드립니다

2023-08-09 10:06 UTC, ghrud92 commented on lib/page/location/controller.dart
> +  Set<dynamic> list_block = {};
혹시 이건 snake case로 작성하신 이유가 있나요?

2023-08-09 10:06 UTC, ghrud92 commented on lib/page/location/controller.dart
> +      final districts = [allDistrict, ...city.districts]
이 districts는 쓰이고 있지 않은 것 같습니다

2023-08-09 10:06 UTC, ghrud92 commented on lib/page/location/controller.dart
> +  List<Map<String, dynamic>> listmap = [];
이 listmap은 혹시 어떤 용도인가요?

2023-08-09 10:06 UTC, ghrud92 commented on lib/page/location/controller.dart
> +  void blockAddList(list1) {
이 함수는 사용되는 곳이 있나요?
사용 되는 곳이 없는 함수면 지워주시고, 있으면 파라미터 타입 명시해주시고 이름도 적절한걸로 변경해주세요

2023-08-09 10:06 UTC, ghrud92 commented on lib/page/location/controller.dart
> +  RxBool settingBtnChk = false.obs;
이 변수는 어떤걸 뜻하는 건가요?

2023-08-09 10:06 UTC, ghrud92 commented on lib/page/location/controller.dart
> +  RxBool selectBlockBool = false.obs;
이 변수는 어떤걸 뜻하나요?

2023-08-09 10:06 UTC, ghrud92 commented on lib/page/location/controller.dart
> +    final String isText1 = list_block
isText1 변수 사용되고 있지 않은 것 같스빈다.

2023-08-09 10:06 UTC, ghrud92 commented on lib/page/location/controller.dart
> +        .map((e) {
e 타입 명시해주시고, expression body 형식으로 변경해주세요

2023-08-09 10:06 UTC, ghrud92 commented on lib/page/location/widget/location_list_item.dart
> +class LocationListItem extends GetView<LocationController> {
여기 아마 GetView 필요 없겠죠?
미리 넣어두신걸까요?

2023-08-09 10:06 UTC, ghrud92 commented on lib/page/location/controller.dart
> +    //blocks.value = [];
주석 지워주세요

2023-08-09 10:06 UTC, ghrud92 commented on lib/page/location/controller.dart
> +  Future<void> selectBlock(int i, int j) async {
여긴 왜 i, j 를 따로 받아야하나요?

2023-08-09 10:06 UTC, ghrud92 commented on lib/page/location/pages.dart
> +                ? SafeBottomButton(
== true 없어도 될 것 같습니다

2023-08-09 10:06 UTC, ghrud92 commented on lib/di.dart
> +class DependencyInjection {
당장 사용하지 않으면 삭제 부탁드립니다

2023-08-10 06:17 UTC, dlaehdrlf4 commented on lib/page/location/pages.dart
> +class LocationPage1 extends GetView<LocationController> {
LocationPage1 => LocationPage로 변경하였습니다.

2023-08-10 06:17 UTC, dlaehdrlf4 commented on lib/page/location/pages.dart
> +import '../../routes/app_routes.dart';
안쓰는 import 삭제하였습니다.

2023-08-10 06:17 UTC, dlaehdrlf4 commented on lib/page/location/pages.dart
> +import '../sample_page.dart';
완료하였습니다.

2023-08-10 06:18 UTC, dlaehdrlf4 commented on lib/page/location/pages.dart
> +  Scaffold(
자동 포맷팅을 통해 업데이트 하였습니다.

2023-08-10 06:33 UTC, dlaehdrlf4 commented on lib/page/location/pages.dart
> +  final _borderSide = const BorderSide(color: Color(0xFFCCCCCC), width: 1);
GetView<LocationController> => StatelessWidget 바꿔서 사용하자는 말씀이신거죠?

2023-08-10 06:35 UTC, dlaehdrlf4 commented on lib/page/location/pages.dart
> +
제거 완료하였습니다.

2023-08-10 06:35 UTC, dlaehdrlf4 commented on lib/page/location/pages.dart
> +
제거 완료하였습니다.

2023-08-10 06:36 UTC, dlaehdrlf4 commented on lib/page/location/controller.dart
> +import 'package:flutter_bloc/flutter_bloc.dart';
제거 하였습니다.

2023-08-10 06:57 UTC, dlaehdrlf4 commented on lib/page/location/controller.dart
> +  Set<dynamic> list_block = {};
카멜코드로 변경하였습니다.

2023-08-10 06:57 UTC, dlaehdrlf4 commented on lib/page/location/controller.dart
> +      final districts = [allDistrict, ...city.districts]
삭제하였습니다.

2023-08-10 06:57 UTC, dlaehdrlf4 commented on lib/page/location/controller.dart
> +  List<Map<String, dynamic>> listmap = [];
사용하지 않아 지워두었습니다.

2023-08-10 06:57 UTC, dlaehdrlf4 commented on lib/page/location/controller.dart
> +  void blockAddList(list1) {
테스트 코드여서 사용하지 않아 지워두었습니다.

2023-08-10 06:57 UTC, dlaehdrlf4 commented on lib/page/location/controller.dart
> +  RxBool settingBtnChk = false.obs;
location/pages.dart 파일에 화면 상태관리가 필요하여 넣어둔 obs 변수입니다.

2023-08-10 06:58 UTC, dlaehdrlf4 commented on lib/page/location/widget/location_list_item.dart
> +class LocationListItem extends GetView<LocationController> {
넵 미리 넣어두었습니다.

2023-08-10 07:16 UTC, dlaehdrlf4 commented on lib/page/location/controller.dart
> +  Future<void> selectBlock(int i, int j) async {
동을 클릭 후 잘못 선택하여 다른 동으로 클릭시 district의 번호를 가지고 동쪽을 다시 뿌려주려고 i,j를 받도록 만들어 놓았습니다.

2023-08-11 02:14 UTC, dlaehdrlf4 commented on lib/di.dart
> +class DependencyInjection {
삭제하였습니다.

2023-08-11 02:14 UTC, dlaehdrlf4 commented on lib/page/location/pages.dart
> +                ? SafeBottomButton(
제거하였습니다.

2023-08-11 02:14 UTC, dlaehdrlf4 commented on lib/page/location/controller.dart
> +  Future<void> selectBlock(int i, int j) async {
하나만 받아도 되어서 하나는 지웠습니다.

2023-08-11 02:14 UTC, dlaehdrlf4 commented on lib/page/location/controller.dart
> +    //blocks.value = [];
삭제 완료하였습니다.

2023-08-12 02:29 UTC, ghrud92 requested changes
변경 완료하신건 resolve 까지 눌러주시면 될 것 같습니다

2023-08-12 02:29 UTC, ghrud92 commented on lib/page/location/pages.dart
> +  final _borderSide = const BorderSide(color: Color(0xFFCCCCCC), width: 1);
아뇨 GetView가 StatelessWidget을 상속받아서 구현했더라구요.
그래서 여기 클래스 내부에서 변수 initialization을 했다고 워닝이 뜨는거구요.
그래서 build() 안에서 변수를  선언하던가, get 함수로 하던가, 아니면 아예 클래스 밖에 `const _borderSide = ...` 로 변경하는게 좋을 것 같아요

2023-08-12 02:29 UTC, ghrud92 commented on lib/page/location/controller.dart
> +  }
이 함수도 안쓰이는 것 같네요

2023-08-12 02:29 UTC, ghrud92 commented on lib/page/location/controller.dart
> +      final allDistrict = District(
District랑 Block은 선택시에 맨 위에 전체 지역 설정하는게 있어야하는데, 그 부분 빠져있나요?
이 변수가 안쓰이고 있네요.

2023-08-12 02:29 UTC, ghrud92 commented on lib/page/location/controller.dart
> +  RxList blocks = <Block>[].obs;
여기 변수도 final로 가능하겠네요 기본 값을 넣어주고 있으니까요

2023-08-12 02:29 UTC, ghrud92 commented on lib/page/location/controller.dart
> +  RxBool select = false.obs;
이 밑으로 다 안쓰이는 변수들이네요
지워주세요

2023-08-12 02:29 UTC, ghrud92 commented on lib/page/location/controller.dart
> +    settingBtnChk.value = false;
주석 지워주세요

2023-08-12 02:29 UTC, ghrud92 commented on lib/page/location/controller.dart
> +  RxBool settingBtnChk = false.obs;
아 이게 설정하기 버튼을 누를 수 있는가에 해당하는 변수군요.
음.. 그럼 settingBtnClickable, isSettingBtnClickable 같은 이름이 더 어울리지 않을까요?

2023-08-12 02:29 UTC, ghrud92 commented on lib/page/location/widget/location_list_item.dart
> +    this.selected = false,
여기는 어떤 이유로 변경하신건가요?
여기라 onTap nullable로 하셨는데, 지금 상태에서는 pages에서 넣어줄 때 이 값들이 다 들어올 것 같아서요
미리 변경하신걸까요?

2023-08-12 02:29 UTC, ghrud92 commented on lib/page/main/controller.dart
> +  RxList<Academy> list = <Academy>[].obs;
final 로 변경해주세요
그리고 list 보다는 어떤 값이 들어있는 리스트인지 알 수 있는 값이 좋을 것 같습니다
academies 나 academyList 같은?

2023-08-12 02:29 UTC, ghrud92 commented on lib/page/main/controller.dart
> +  final mainRepository = Get.put(AcademyRepository());
academyRepository 가 맞겠네요

2023-08-12 02:29 UTC, ghrud92 commented on lib/page/main/pages.dart
> +              label: '${controller.myLocation.value}',
여기 myLocation에 항상 값이 있지 않나요?

2023-08-12 02:29 UTC, ghrud92 commented on lib/page/main/pages.dart
> +                  child: const Padding(
여기 const 지워주셔야 할 것 같아요
밑에 Column에 빨간 줄 그어지네요

2023-08-12 02:29 UTC, ghrud92 commented on lib/page/sign_up/controller.dart
> +  void onInit() {
이거 지워도 될 것 같습니다

2023-08-12 02:29 UTC, ghrud92 commented on lib/page/sample_page.dart
> +import 'package:flutter/material.dart';
이거 안쓰이는 페이지죠?
삭제 부탁드립니다

2023-08-12 02:29 UTC, ghrud92 commented on test/auth/auth_cubit_test.dart
> +// import 'package:ballet_for_all_flutter/auth/auth_cubit.dart';
삭제해주세요

2023-08-12 02:29 UTC, ghrud92 commented on lib/repository/academy/academy_repository.dart
> +import 'package:cloud_firestore/cloud_firestore.dart';
테스트용 모킹 편하게 하려고 만들어둔건데, 일단 변경하신대로 합쳐서 가시죠

2023-08-12 02:29 UTC, ghrud92 commented on test/page/location/cubit/location_cubit_test.dart
> +// import 'package:ballet_for_all_flutter/page/location/cubit/location_cubit.dart';
얘도 삭제해주세요

2023-08-12 02:29 UTC, ghrud92 commented on lib/repository/city/district.dart
> +  const District({required this.name, required this.blocks,this.key = 0});
key는 어떤 용도인가요?
그리고 여기 포멧팅이 제대로 안되어있네요

2023-08-12 02:29 UTC, ghrud92 commented on lib/repository/academy/academy_repository.dart
> +    final academyJsonList = await FirebaseFirestore.instance.collection("academies").get();
큰따옴표 말고 작은 따옴표로 바꿔주세요

2023-08-12 02:29 UTC, ghrud92 commented on lib/repository/city/location_repository.dart
> +    final snapshot = await FirebaseFirestore.instance.collection("location").get();
큰따옴표 말고 작은 따옴표로 바꿔주세요

2023-08-12 02:29 UTC, ghrud92 commented on lib/repository/city/location_repository.dart
> +import 'package:cloud_firestore/cloud_firestore.dart';
CityRepository를 LocationRepository로 변경하실 거라면, 기존 CityRepository, FirestoreCityRepository 삭제해주세요

2023-08-12 02:29 UTC, ghrud92 commented on lib/routes/app_pages.dart
> +        binding: MainBinding()),
MainView에 const 붙여주세요

2023-08-12 02:29 UTC, ghrud92 commented on lib/services/storeage_services.dart
> +import 'package:get/get.dart';
이건 어떤 용도인가요?
지금 사용되지 않는거면 삭제 부탁드립니다

2023-08-12 02:29 UTC, ghrud92 commented on lib/main.dart
> +        debugShowCheckedModeBanner: false,
이거는 개발시엔 debug 표시 있는게 더 낫지 않을까요?

2023-08-12 02:29 UTC, ghrud92 commented on pubspec.yaml
> +
삭제해주세요

2023-08-12 07:14 UTC, ghrud92 commented on lib/page/location/controller.dart
> +class LocationController extends GetxController {
파일 이름이 클래스명을 따라가면 좋을 것 같습니다.
location_controller.dart, main_controller.dart 등으로 변경하는게 어떨까요?

2023-08-12 07:15 UTC, ghrud92 commented on lib/page/location/controller.dart
> +class LocationController extends GetxController {
binding, pages 도 각자 클래스명을 따라가도록요

2023-08-13 02:26 UTC, ghrud92 commented on lib/routes/app_routes.dart
> +abstract class Routes {
일단 여기는 abstract class가 아닐 것 같구요.

한가지 의견이 있는데, 이 파일에 라우팅 경로를 다 모아놓기 보다는 각 페이지별로 static const routeName 같은 값을 갖고있는게 어떨까요?

'academies/:id' 이런 경우를 생각해보면 페이지에 
routeName = 'academies/:id'
generateRoute(String id) => 'academies/$id'
이런 식으로 표현하는 경우가 생길 것 같아서요

2023-08-17 06:34 UTC, dlaehdrlf4 commented on lib/page/location/pages.dart
> +  final _borderSide = const BorderSide(color: Color(0xFFCCCCCC), width: 1);
클래스 밖에서 선언했습니다.

2023-08-17 06:35 UTC, dlaehdrlf4 commented on lib/page/location/pages.dart
> +  final _borderSide = const BorderSide(color: Color(0xFFCCCCCC), width: 1);
클래스 밖에서 처리해두었습니다.

2023-08-17 06:35 UTC, dlaehdrlf4 commented on lib/page/location/pages.dart
> +
제거하였습니다.

2023-08-17 06:35 UTC, dlaehdrlf4 commented on lib/page/location/controller.dart
> +  RxBool settingBtnChk = false.obs;
isSettingBtnClickable 변경해보겠습니다.

2023-08-17 06:36 UTC, dlaehdrlf4 commented on lib/page/location/controller.dart
> +  }
const _borderSide를 클래스 밖으로 변경하였고 selectBlock 함수는 location pages.dart에서 사용되어지고 있습니다.

2023-08-17 06:36 UTC, dlaehdrlf4 commented on lib/page/location/controller.dart
> +      final allDistrict = District(
전체지역 설정하는 부분 추가하였습니다.

2023-08-17 06:36 UTC, dlaehdrlf4 commented on lib/page/location/controller.dart
> +  RxList blocks = <Block>[].obs;
final로 변경처리하였습니다.

2023-08-17 06:36 UTC, dlaehdrlf4 commented on lib/page/location/controller.dart
> +  RxBool select = false.obs;
안쓰는 변수 삭제처리 하였습니다.

2023-08-17 06:36 UTC, dlaehdrlf4 commented on lib/page/location/controller.dart
> +    settingBtnChk.value = false;
주석 제거완료

2023-08-17 06:36 UTC, dlaehdrlf4 commented on lib/page/location/widget/location_list_item.dart
> +    this.selected = false,
isSettingBtnClickable 변경처리 하였습니다.
required로 무조건 들어오게 넣어두었습니다.

2023-08-17 06:36 UTC, dlaehdrlf4 commented on lib/page/main/controller.dart
> +  RxList<Academy> list = <Academy>[].obs;
AcademyList로 변경 완료하였습니다.

2023-08-17 06:36 UTC, dlaehdrlf4 commented on lib/page/main/controller.dart
> +  final mainRepository = Get.put(AcademyRepository());
넵 그게 맞는거 같아요 바꿔놓았습니다.

2023-08-17 06:37 UTC, dlaehdrlf4 commented on lib/page/main/pages.dart
> +              label: '${controller.myLocation.value}',
항상 값이 있습니다 label: controller.myLocation.value 이렇게 변경 처리 해두겠습니다.

2023-08-17 06:37 UTC, dlaehdrlf4 commented on lib/page/main/pages.dart
> +                  child: const Padding(
const 지웠습니다.

2023-08-17 06:37 UTC, dlaehdrlf4 commented on lib/page/sign_up/controller.dart
> +  void onInit() {
넵 지웠습니다.

2023-08-17 06:37 UTC, dlaehdrlf4 commented on lib/page/sample_page.dart
> +import 'package:flutter/material.dart';
안쓰는 페이지라 삭제 처리 하겠습니다.

2023-08-17 06:37 UTC, dlaehdrlf4 commented on test/auth/auth_cubit_test.dart
> +// import 'package:ballet_for_all_flutter/auth/auth_cubit.dart';
삭제하였습니다.

2023-08-17 06:37 UTC, dlaehdrlf4 commented on lib/repository/academy/academy_repository.dart
> +import 'package:cloud_firestore/cloud_firestore.dart';
네엡 알겠습니다.

2023-08-17 06:37 UTC, dlaehdrlf4 commented on test/page/location/cubit/location_cubit_test.dart
> +// import 'package:ballet_for_all_flutter/page/location/cubit/location_cubit.dart';
삭제하였습니다.

2023-08-17 06:37 UTC, dlaehdrlf4 commented on lib/repository/city/district.dart
> +  const District({required this.name, required this.blocks,this.key = 0});
key 테스트 용도로 추가 했던거 같고 쓰지 않아서 제거 하였습니다 추가로 포멧팅도 완료하였습니다.

2023-08-17 06:37 UTC, dlaehdrlf4 commented on lib/repository/academy/academy_repository.dart
> +    final academyJsonList = await FirebaseFirestore.instance.collection("academies").get();
바꿔두었습니다.

2023-08-17 06:37 UTC, dlaehdrlf4 commented on lib/repository/city/location_repository.dart
> +    final snapshot = await FirebaseFirestore.instance.collection("location").get();
작은 따옴표로 바꿔두었습니다.

2023-08-17 06:37 UTC, dlaehdrlf4 commented on lib/repository/city/location_repository.dart
> +import 'package:cloud_firestore/cloud_firestore.dart';
넵 제거해두었습니다.

2023-08-17 06:38 UTC, dlaehdrlf4 commented on lib/routes/app_pages.dart
> +        binding: MainBinding()),
const 추가 완료

2023-08-17 06:38 UTC, dlaehdrlf4 commented on lib/services/storeage_services.dart
> +import 'package:get/get.dart';
나중에 추가할 부분이 있어서 추가하였는데 일단 삭제 해두겠습니다.

2023-08-17 06:38 UTC, dlaehdrlf4 commented on lib/main.dart
> +        debugShowCheckedModeBanner: false,
개발시에는 있는게 좋을거 같아서 위에 코드 제거하였습니다.

2023-08-17 06:38 UTC, dlaehdrlf4 commented on pubspec.yaml
> +
삭제하였습니다.

2023-08-17 06:38 UTC, dlaehdrlf4 commented on lib/page/location/controller.dart
> +class LocationController extends GetxController {
넵 좋은 의견인거 같습니다 바꿔서 올려놓도록 하겠습니다.

2023-08-17 06:38 UTC, dlaehdrlf4 commented on lib/routes/app_routes.dart
> +abstract class Routes {
페이지별로 만들어서 사용하게 만들었습니다.

2023-08-17 12:26 UTC, ghrud92 requested changes

2023-08-17 12:26 UTC, ghrud92 commented on lib/page/location/location_controller.dart
> +    Get.toNamed(MainView.routeName,
여기 block name만 넘기면 '전체' 이렇게 갈 수도 있을 것 같아요

지역 관리를 SharedPreferences로 할 예정인거니 당장은 todo만 남겨주셔도 되구요

2023-08-17 12:26 UTC, ghrud92 commented on lib/page/location/location_controller.dart
> +  final selectedCity = 0.obs;
어차피 여기서 기본 값을 세팅하고 있으니 아예 -1 을 넣을까요?
onInit에서 그 부분을 삭제하구요

2023-08-17 12:26 UTC, ghrud92 commented on lib/page/location/location_controller.dart
> +  final isSettingBtnClickable = false.obs;
이거 selectedBlock != -1 인 경우인 것 같은데, Rx 값들은 get 함수로 표현 가능한가요..?

bool get isSettionBtnClickable => selectedBlock.value != -1;

이런 느낌으로 가능하면 get 함수로 바꾸는게 더 좋을 것 같아서요
근데 이런 경우에 selectedBlock 값이 변경되면 UI에 바로 반영되는지 확인이 필요하겠네요

2023-08-17 12:26 UTC, ghrud92 commented on lib/page/location/location_pages.dart
> +                        decoration: BoxDecoration(
lint warning 뜨네요
BoxDecoration에 const 붙여주세요

2023-08-17 12:26 UTC, ghrud92 commented on lib/page/location/location_pages.dart
> +                        decoration: BoxDecoration(
여기도 const 요

2023-08-17 12:26 UTC, ghrud92 commented on lib/page/location/location_pages.dart
> +                        decoration: BoxDecoration(
여기도 const요

2023-08-17 12:26 UTC, ghrud92 commented on lib/page/main/main_controller.dart
> +  final AcademyList = <Academy>[].obs;
camel case로 변경해주세요

2023-08-17 12:26 UTC, ghrud92 commented on lib/page/main/main_controller.dart
> +
빈 줄 없애주세요

2023-08-17 12:26 UTC, ghrud92 commented on lib/page/main/main_controller.dart
> +    myLocation.value = myLocationArg;
dynamic... 이건 어쩔 수 없이 이렇게 써야하는군요.

2023-08-17 12:26 UTC, ghrud92 commented on lib/page/location/location_pages.dart
> +import 'package:flutter/material.dart';
파일 이름도 클래스따라 location_page.dart가 맞지 않을까요?

2023-08-17 12:26 UTC, ghrud92 commented on lib/page/main/main_pages.dart
> +class MainView extends GetView<MainController> {
클래스 이름 변경해주세요

2023-08-17 12:26 UTC, ghrud92 commented on lib/page/main/main_pages.dart
> +                      children: [
lint warning 뜨네요
children에 const 붙여주세요

2023-08-17 12:26 UTC, ghrud92 commented on lib/page/main/main_pages.dart
> +                    padding: EdgeInsets.only(left: 30),
const 붙여주세요

2023-08-17 12:26 UTC, ghrud92 commented on lib/page/sign_up/sign_up_pages.dart
> +class SignUpView extends GetView<SignUpPageController> {
SignUpPage로 변경해주세요

2023-08-17 12:26 UTC, ghrud92 commented on lib/page/sign_up/sign_up_pages.dart
> +import 'package:flutter/material.dart';
lib/sign_up/view 폴더 삭제 부탁드립니다

2023-08-17 12:26 UTC, ghrud92 commented on lib/repository/academy/academy_repository.dart
> +class AcademyRepository extends FirestoreCollection {
안쓰이게된 lib/firebase/firestore_academies/, lib/firebase/firestore_locations/, lib/firebase/firebase_client 삭제 부탁드립니다

2023-08-17 12:26 UTC, ghrud92 commented on lib/main.dart
> +        initialBinding: AppBinding(),
기존에 textScaleFactor 1.0 넣던 것 있었는데, 혹시 그것도 여기에 적용 가능할까요?

2023-08-17 12:27 UTC, ghrud92 commented on lib/page/location/location_controller.dart
> +    Get.toNamed(MainView.routeName,
이건 그냥 넘어가도 될 것 같습니다!

2023-08-17 23:48 UTC, dlaehdrlf4 commented on lib/page/location/location_controller.dart
> +  final selectedCity = 0.obs;
이부분은 0으로 초기화하지 않고 -1로 초기화를 진행시 Rxint형태가 아닌 int형태로 받아들여져 반응형 상태관리 변수처리가 되지 않는 부분이라 현재 상태를 유지해야할거 같습니다.

2023-08-17 23:53 UTC, dlaehdrlf4 commented on lib/page/location/location_controller.dart
> +  final isSettingBtnClickable = false.obs;
Rx타입의 변수는 UI 화면상에서 상태가 변경시 바로 변경되게 하려면 Obx(()=>Widget) 형식으로 감싸면 값 변경시 UI에서 바로 적용되는걸 확인할수 있습니다.

2023-08-17 23:59 UTC, dlaehdrlf4 commented on lib/page/sign_up/sign_up_pages.dart
> +import 'package:flutter/material.dart';
삭제하였습니다.

2023-08-17 23:59 UTC, dlaehdrlf4 commented on lib/page/sign_up/sign_up_pages.dart
> +class SignUpView extends GetView<SignUpPageController> {
변경하였습니다.

2023-08-18 00:00 UTC, dlaehdrlf4 commented on lib/repository/academy/academy_repository.dart
> +class AcademyRepository extends FirestoreCollection {
삭제완료하였습니다.

2023-08-18 03:35 UTC, dlaehdrlf4 commented on lib/main.dart
> +        initialBinding: AppBinding(),
적용하였습니다.

2023-08-18 03:35 UTC, dlaehdrlf4 commented on lib/page/main/main_pages.dart
> +                    padding: EdgeInsets.only(left: 30),
붙였습니다.

2023-08-18 03:47 UTC, dlaehdrlf4 commented on lib/page/location/location_controller.dart
> +  final isSettingBtnClickable = false.obs;
isSettionBtnClickable 이걸 없애고 selectedBlock.value 이걸 통해 설정하기 버튼 보이게 수정했습니다.

2023-08-18 03:48 UTC, dlaehdrlf4 commented on lib/page/location/location_pages.dart
> +                        decoration: BoxDecoration(
붙였습니다.

2023-08-18 03:48 UTC, dlaehdrlf4 commented on lib/page/location/location_pages.dart
> +                        decoration: BoxDecoration(
붙였습니다.

2023-08-19 06:40 UTC, ghrud92 approved these changes
제가 지난번에 코멘트를 너무 많이 달아서 중간에 숨겨진 코멘트들을 못보신 것 같습니다.
그것들만 간단하게 반영해주시고 바로 넣으시면 될 것 같아요.
고생하셨습니다!

2023-08-19 06:40 UTC, ghrud92 commented on lib/page/location/location_controller.dart
> +  final selectedCity = 0.obs;
아하 그렇군요

2023-08-19 06:40 UTC, ghrud92 commented on lib/page/main/main_controller.dart
> +  final AcademyList = <Academy>[].obs;
여기 코멘트도 반영해주세요

2023-08-19 06:40 UTC, ghrud92 commented on lib/page/main/main_controller.dart
> +
여기 코멘트도 반영해주세요

2023-08-19 06:40 UTC, ghrud92 commented on lib/page/location/location_pages.dart
> +import 'package:flutter/material.dart';
여기 코멘트도 반영해주세요

2023-08-19 06:40 UTC, ghrud92 commented on lib/page/main/main_pages.dart
> +                      children: [
여기 코멘트도 반영해주세요

2023-08-19 06:41 UTC, ghrud92 commented
https://github.com/ballet-for-all/ballet_for_all_flutter/pull/25#pullrequestreview-1582455157 
여기의 hidden conversation을 봐주시면 됩니다

2023-08-21 12:09 UTC, dlaehdrlf4 commented on lib/page/main/main_controller.dart
> +  final AcademyList = <Academy>[].obs;
변경완료

2023-08-21 12:09 UTC, dlaehdrlf4 commented on lib/page/location/location_pages.dart
> +import 'package:flutter/material.dart';
완료

2023-08-21 12:09 UTC, dlaehdrlf4 commented on lib/page/main/main_pages.dart
> +                      children: [
반영완료

2023-08-21 12:14 UTC, dlaehdrlf4 commented on lib/page/main/main_pages.dart
> +class MainView extends GetView<MainController> {
클래스 이름 변경

2023-08-21 12:15 UTC, dlaehdrlf4 commented on lib/page/main/main_controller.dart
> +
반영완료

2023-08-21 12:16 UTC, merged