Edfj 117
ballet-for-all/ballet_for_all_flutter pull request #34
Opened 2023-09-30 06:08 UTC by dlaehdrlf4

현재위치 가져와서 UI에 반영하기 완료

2023-09-30 07:57 UTC, ghrud92 requested changes

2023-09-30 07:57 UTC, ghrud92 commented on ios/Runner/Info.plist
> +	<key>NSLocationWhenInUseUsageDescription</key>
밑의 다른 옵션들처럼 들여쓰기 맞춰주세요

2023-09-30 07:57 UTC, ghrud92 commented on pubspec.yaml
> +  kakao_flutter_sdk: ^1.5.0
kakao sdk 는 지금 안쓰고 있지 않나요?

2023-09-30 07:57 UTC, ghrud92 commented on lib/page/location/location_pages.dart
> +              controller.isLoading.value == false
!controller.isLoading.value 혹은 controller.isLoading.value를 바로 사용해주세요
nullable 한 값이 아니니 == false로 검사할 필요 없어보입니다

2023-09-30 07:57 UTC, ghrud92 commented on lib/page/location/location_controller.dart
> +  String city = '';
이 변수들 class member로 선언할게 아니라, 각 함수 안에 선언해서 사용할 수 있지 않을까요?

2023-09-30 07:57 UTC, ghrud92 commented on lib/page/location/location_controller.dart
> +    Future.delayed(const Duration(seconds: 0), () {
이 delay는 혹시 왜 필요한가요?

2023-09-30 07:57 UTC, ghrud92 commented on lib/page/location/location_controller.dart
> +    LocationPermission permission = await Geolocator.requestPermission();
permission 변수 사용하는 곳이 없어보입니다

2023-09-30 07:57 UTC, ghrud92 commented on lib/page/location/location_controller.dart
> +      "authorization": "KakaoAK bcae6ea307f8c461276037fb3cf73651",
작은 따옴표로 변경해주세요

그리고 public repository라서 secret 값이 여기 박혀있는게 안좋을 것 같은데, dotenv 사용하는 방식으로 변경해주실 수 있을까요?
https://pub.dev/packages/flutter_dotenv
assets에 .env 파일 추가해주시고 .gitignore에 해당 파일 무시하도록 해주시면 될 것 같습니다.

아니면 다른 좋은 라이브러리있으면 그걸 사용해주셔도 좋습니다.

2023-09-30 07:57 UTC, ghrud92 commented on lib/page/location/location_controller.dart
> +    final list = result['documents'][0]['address_name'].toString().split(' ');
list 안쓰이네요

2023-09-30 07:57 UTC, ghrud92 commented on lib/page/location/location_controller.dart
> +    if (result['documents'][0]['region_2depth_name'].toString().length > 3) {
이 부분 region_2depth_name, region_3depth_name을 바로 district와 block에서 조회하면 에러 나는 부분이 있는건가요?

2023-09-30 07:57 UTC, ghrud92 commented on lib/page/location/location_controller.dart
> +            if (cities[i].districts[j].blocks[k].name == dong) {
여기서 block의 이름만 채크하면 이름이 동일한 block이 여러개 있을 경우에 문제가 생기지 않을까요?
city, district, block 의 이름이 전부 같을 때만 설정해야 할 것 같습니다.

2023-09-30 07:57 UTC, ghrud92 commented on lib/page/location/location_controller.dart
> +    city = result['documents'][0]['region_1depth_name'].toString();
result['documents'][0] 이 여러곳에서 쓰이는데 address 같은 변수로 선언하면 어떨까요?
그리고 implicit dynamic 이라고 워닝이 다 떠있는데, 워닝 있는 줄만 ignore 시키던가 아니면 캐스팅을 해주는게 좋아보입니다.

2023-09-30 07:57 UTC, ghrud92 commented on lib/page/location/location_pages.dart
>                          // TODO(ghrud92): 위치 권한 요청 & 현재 위치로 동네 변경
이 todo가 지금 작업하신 내용이니 지워주세요

2023-09-30 07:58 UTC, ghrud92 commented
comment가 많아서 중간에 2개 hidden 처리 되어있습니다
다 확인 부탁드려요

2023-09-30 08:33 UTC, dlaehdrlf4 commented on lib/page/location/location_controller.dart
> +    if (result['documents'][0]['region_2depth_name'].toString().length > 3) {
예를들어 경기도 수원시 권선구 탑동이라고하면 region_2depth_name 값이 수원시 권선구까지 나오고 region_3depth_name 이부분이 탑동이 나오게 됩니다. 하지만 지금 district는 수원시만 가지고 있고 block은 권선구 탑동 이런식으로 들고 있어서 분기를 태우게 나눴습니다.

2023-09-30 08:33 UTC, dlaehdrlf4 commented on pubspec.yaml
> +  kakao_flutter_sdk: ^1.5.0
main쪽에서 그 kakao sdk를 사용하고 있어서 추가하였습니다.

2023-09-30 08:53 UTC, dlaehdrlf4 commented on lib/page/location/location_pages.dart
>                          // TODO(ghrud92): 위치 권한 요청 & 현재 위치로 동네 변경
제거해두었습니다.

2023-09-30 08:54 UTC, dlaehdrlf4 commented on lib/page/location/location_controller.dart
> +    city = result['documents'][0]['region_1depth_name'].toString();
변수로 선언하였고 워닝줄 ignore처리 해두었습니다.

2023-09-30 08:55 UTC, dlaehdrlf4 commented on lib/page/location/location_controller.dart
> +            if (cities[i].districts[j].blocks[k].name == dong) {
그럴수 있겠네요 3가지 부분을 다 체크하도록 로직 수정하였습니다.

2023-09-30 08:55 UTC, dlaehdrlf4 commented on lib/page/location/location_controller.dart
> +    final list = result['documents'][0]['address_name'].toString().split(' ');
넵 제거하였습니다.

2023-09-30 08:55 UTC, dlaehdrlf4 commented on lib/page/location/location_controller.dart
> +    Future.delayed(const Duration(seconds: 0), () {
검색부분하면서 필요할거 같아서 추가해두었었는데 필요 없어보여 제거 하였습니다.

2023-09-30 08:56 UTC, dlaehdrlf4 commented on lib/page/location/location_controller.dart
> +  String city = '';
각 함수에 배치하는게 좋은거 같네요 수정해두었습니다.

2023-09-30 08:56 UTC, dlaehdrlf4 commented on lib/page/location/location_pages.dart
> +              controller.isLoading.value == false
수정하였습니다.

2023-09-30 08:56 UTC, dlaehdrlf4 commented on ios/Runner/Info.plist
> +	<key>NSLocationWhenInUseUsageDescription</key>
넵 수정하였습니다;.

2023-09-30 10:23 UTC, ghrud92 commented on pubspec.yaml
> +  kakao_flutter_sdk: ^1.5.0
거기서 init만 하고 쓰는데는 없지않나요?
다음 작업을 위한건가요?

2023-09-30 10:23 UTC, ghrud92 commented on ios/Runner/Info.plist
> +	<key>NSLocationWhenInUseUsageDescription</key>
그대로인 것 같습니다
다시 확인해주세요

2023-09-30 10:37 UTC, ghrud92 requested changes
conflict도 해결해서 올려주세요

2023-09-30 10:37 UTC, ghrud92 commented on lib/page/location/location_controller.dart
> +    Map result = json.decode(responseGps.body);
변경되는 값이 아니니 final 붙여주세요

2023-09-30 10:37 UTC, ghrud92 commented on lib/page/location/location_controller.dart
> +    String gpsUrl =
변경되는 값이 아니니 final 붙여주세요

2023-09-30 10:37 UTC, ghrud92 commented on lib/page/location/location_controller.dart
> +    Position position = await Geolocator.getCurrentPosition(
변경되는 값이 아니니 final 붙여주세요변경되는 값이 아니니 final 붙여주세요

2023-10-01 06:41 UTC, dlaehdrlf4 commented on ios/Runner/Info.plist
> +	<key>NSLocationWhenInUseUsageDescription</key>
[23f934d] 이 커밋된 번호로 수정하였는데 안되었을까요?

2023-10-01 06:41 UTC, dlaehdrlf4 commented on pubspec.yaml
> +  kakao_flutter_sdk: ^1.5.0
카카오 로그인 사용시 필요할거 같습니다.

2023-10-01 06:46 UTC, dlaehdrlf4 commented on lib/page/location/location_controller.dart
> +    LocationPermission permission = await Geolocator.requestPermission();
저 permission 부분을 쓰지 않으면 현재위치 가져올때 오류가 납니다 저걸 쓰는 이유는 그 현재 위치를 사용하기 위해서 이번만 허용,앱을 사용하는 동안 허용, 허용안함을 띄우기 위해 필요합니다.

2023-10-01 07:46 UTC, dlaehdrlf4 commented on lib/page/location/location_controller.dart
> +      "authorization": "KakaoAK bcae6ea307f8c461276037fb3cf73651",
dotenv 추가하여 커밋했습니다.

2023-10-01 07:47 UTC, dlaehdrlf4 commented on lib/page/location/location_controller.dart
> +    Map result = json.decode(responseGps.body);
final 추가하였습니다.

2023-10-01 07:47 UTC, dlaehdrlf4 commented on lib/page/location/location_controller.dart
> +    String gpsUrl =
final 추가하였습니다.

2023-10-01 07:47 UTC, dlaehdrlf4 commented on lib/page/location/location_controller.dart
> +    Position position = await Geolocator.getCurrentPosition(
final 추가하였습니다.

2023-10-01 07:49 UTC, ghrud92 commented on lib/page/location/location_controller.dart
> +    LocationPermission permission = await Geolocator.requestPermission();
변수를 둘 필요는 없지 않을까요?
await Geolocator.requestPermission(); 만 사용해도 충분할 것 같습니다.

2023-10-01 07:56 UTC, ghrud92 commented on ios/Runner/Info.plist
> +	<key>NSLocationWhenInUseUsageDescription</key>
```
                  <key>NSLocationWhenInUseUsageDescription</key>
        <string>This app needs access to location when open.</string>
        <key>NSLocationAlwaysUsageDescription</key>
        <string>This app needs access to location when in the background.</string>
		<key>CADisableMinimumFrameDurationOnPhone</key>
		...
```
제가 에디터에서는 이런식으로 들여쓰기가 안맞기는 하는데, 중요한건 아니니 그냥 넘어가시죠

2023-10-01 08:00 UTC, ghrud92 commented
.env 파일 asset 밑으로 넣어주시겠어요?
그리고 .env 파일 구글 드라이브에 업로드 해주시고,
README에 Firebase 설정하는 부분처럼 Kakao SDK 설정 부분 만들어서 드라이브에서 받아서 세팅하라고 적어주세요

2023-10-01 08:01 UTC, ghrud92 approved these changes

2023-10-04 10:57 UTC, merged