네 동네 설정하기 화면 검색 구현 완료
ballet-for-all/ballet_for_all_flutter pull request #38
Opened 2023-10-07 02:28 UTC by dlaehdrlf4

2023-10-11 10:22 UTC, ghrud92 requested changes

2023-10-11 10:22 UTC, ghrud92 commented on lib/page/location/location_pages.dart
> +import '../main/main_pages.dart';
이거 안쓰이는 것 같네요
삭제해주세요

2023-10-11 10:22 UTC, ghrud92 commented on lib/page/location/location_controller.dart
> +    if (str[2] == '전체') {
searchListText[index].toString()에 '전체'가 포함되어 있으면 전체 이전의 단어를 location에 넣어주는게 맞지않을까요?
'서울특별시 종로구 전체' => '종로구'

2023-10-11 10:22 UTC, ghrud92 commented on lib/page/location/location_pages.dart
> +                      child: controller.searchListText.length == 1
1개일 경우에 이렇게 처리를 하면, '청운동' 처럼 정말 검색 내용과 일치하는 동이 하나만 나왔을 때도 검색 결과가 없다고 나옵니다.
검색 결과가 없을 때 검색 텍스트를 검색 결과 리스트에 추가하지 말고, 89라인에서 controller.searchListText.isEmpty로 확인 후에 검색 결과 없음을 보여주는게 어떨까요?

2023-10-11 10:22 UTC, ghrud92 commented on lib/page/location/location_controller.dart
> +    for (int i = 0; i < cities.length; i++) {
for (final city in cities) {}
처럼 iteration 도는게 더 읽기 편할 것 같습니다.

2023-10-11 10:22 UTC, ghrud92 commented on lib/page/location/location_controller.dart
> +          allLocation.add(
세종시는 아예 검색 목록에 나오지 않네요.
확인 부탁드립니다

2023-10-13 05:44 UTC, dlaehdrlf4 commented on lib/page/location/location_pages.dart
> +import '../main/main_pages.dart';
제거해두겠습니다.

2023-10-13 05:45 UTC, dlaehdrlf4 commented on lib/page/location/location_controller.dart
> +    if (str[2] == '전체') {
음... 그게 사용자 입장에서는 식별하기 좋을수 있겠네요

2023-10-13 06:09 UTC, dlaehdrlf4 commented on lib/page/location/location_pages.dart
> +                      child: controller.searchListText.length == 1
넵 그렇네요 확인하고 수정하였습니다.

2023-10-13 06:28 UTC, dlaehdrlf4 commented on lib/page/location/location_controller.dart
> +    for (int i = 0; i < cities.length; i++) {
넵 수정해놓겠습니다.

2023-10-20 11:21 UTC, dlaehdrlf4 commented on lib/page/location/location_controller.dart
> +          allLocation.add(
세종특별자치시로 검색하면 나오게 되어있습니다.

2023-10-21 10:02 UTC, ghrud92 approved these changes
코맨트 드린것만 해결하고 넣어주세요

2023-10-21 10:02 UTC, ghrud92 commented on lib/page/location/location_controller.dart
> +            if (district.name != '전체') {
block이 '전체' 인 경우도 빼야하지 않을까요?

2023-10-21 10:02 UTC, ghrud92 commented on lib/page/location/location_controller.dart
>    Future<void> selectCity(int i) async {
blocks를 empty list로 만들어줘야 할 것 같습니다.
지금은 서울특별시 중구 눌렀다가, 부산광역시를 누르면 서울 중구의 동들이 그대로 보이네요.

2023-10-23 00:04 UTC, merged